### ISSUE TITLE
"Unable to find Allure implementation" error when running Mocha test in Webstorm

### ISSUE THREAD

**Issue by azakordonets** [sskorol/ts-test-decorators#18]
When i'm trying to run the mocha tests with ts-test-decorators and allure-mocha integration: 
```
/Users/andrew/.nvm/versions/node/v12.14.1/bin/node /Users/andrew/end-2-end-api-tests-typescript/node_modules/mocha/bin/mocha --require ts-node/register --reporter allure-mocha --ui bdd --reporter "/Users/andrew/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/202.7660.23/WebStorm.app/Contents/plugins/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js" /Users/andrew/end-2-end-api-tests-typescript/tests/create-user.spec.ts
```

Webstorm is basically overriding the `reporter` option and therefore we're getting  following error: 

```
Error: Unable to find Allure implementation
    at getAllure (node_modules/ts-test-decorators/src/index.ts:132:11)
    at Function.callable (node_modules/ts-test-decorators/src/index.ts:49:28)
    at Function.descriptor.value (node_modules/ts-test-decorators/src/index.ts:54:25)
    at Context.<anonymous> (tests/create-user.spec.ts:13:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
```

Is there a way on how to pass Allure implementation to ts-test-decorator with Webstorm limitations bypassing ? 

Our `before` method looks like this : 
```typescript
import { allure } from 'allure-mocha/runtime'
import type { MochaAllure } from 'allure-mocha/runtime'
import { decorate } from 'ts-test-decorators'

before('Run before', async () => {
    decorate<MochaAllure>(allure)
// we have some async code down the method. 
}
```

**Comment by sskorol** [comment]
I believe you may want to take a look at the following projects to support what you're asking for:
- https://github.com/glenjamin/mocha-multi
- https://github.com/stanleyhlng/mocha-multi-reporters

**Comment by azakordonets** [comment]
Actually i found this answer on Stackoverflow - https://stackoverflow.com/questions/44575915/webstorm-not-able-to-change-default-mocha-reporter/44584954?noredirect=1#comment76256282_44584954

```
WebStorm uses its own reporter to represent test results as a tree view with filters/navigation etc. So you can't use other reporters when using Mocha integration. If you prefer getting output produced by other reporters instead, you have to run Mocha with Node.js run configuration
```

Which is a bummer. Have you had such issues in Webstorm as well, or you don't use Webstorm for javascript projects ?

**Comment by sskorol** [comment]
I always use npm run configuration in WebStorm. So probably that's why I haven't seen such issues before. On the other hand, I don't understand people's complaints about reporters. Multiple reports' specification is not something that works out of the box in Mocha w/o hacks. That's why I gave you links to the projects which allow passing several reporters from cli.

**Comment by azakordonets** [comment]
Yeah, from what i understood, it's impossible to use any other custom mocha reporter from Webstorm, because it's attached with nails for Webstorm functionality. Anyway, thanks for the tips :)
