### ISSUE TITLE
[Bug] Type 'MochaAllure' does not satisfy the constraint 'Allure' error

### ISSUE THREAD

**Issue by viraxslot** [sskorol/ts-test-decorators#19]
Hi, I tried to add `ts-test-decorators` to my project and faced problem:
1. If install dependencies from scratch there is a typescript error:
```src/test/test.spec.ts:15:18 - error TS2344: Type 'MochaAllure' does not satisfy the constraint 'Allure'.
  Property 'runtime' is protected but type 'Allure' is not a class derived from 'Allure'.
decorate<MochaAllure>(allure);
```
2. If copy package-lock.json from the [repo](https://github.com/sskorol/mocha-allure2-example) - it works just fine.

Repo to reproduce the problem:
1. There is problem on `master` [branch](https://github.com/viraxslot/try-decorators)
2. There is no problem on `no-problem-with-original-deps` [branch](https://github.com/viraxslot/try-decorators/tree/no-problem-with-original-deps)

[Here is PR](https://github.com/viraxslot/try-decorators/pull/1) to see the difference in package-lock.

Steps to reproduce:
1. Checkout master, npm i
2. Run tsc
3. See the problem

4. Checkout no-problem-with-original-deps
5. Delete node_modules, npm i
6. Run tsc
7. See no problem

Hope it'll be fixed :) Thanks!

**Comment by sskorol** [comment]
@viraxslot hi, the lock file is pushed to the repo to persist specified versions. When you `run install`, npm updates existing dependencies to newer versions. If you want to use the existing lock file, run `npm ci` instead.

**Comment by viraxslot** [comment]
@sskorol Yeah, I know, thanks. It's just a problem when trying to install dependencies from the scratch: beta-9 version is installed and your package just doesn't work with it. Honestly I've never copy package-lock from other repos.

I've found the workaround: to use versions without ^:
"allure-js-commons": "2.0.0-beta.7",
"allure-mocha": "2.0.0-beta.7"

Badly that ^version is a default :)

**Comment by sskorol** [comment]
But why does your lock-file contain `2.0.0-beta.9`? How did you generate it? And yes, npm will update deps from the locked version, as there's a `^` symbol that force-bumps dependencies.

**Comment by viraxslot** [comment]
Because npm with ^2.0.0-beta.7 notation should install any patch version, and it installs 2.0.0-beta.9, but it has breaking changes.

**Comment by sskorol** [comment]
Decorators are now officially in allure-js since [v2.0.0-beta.11](https://github.com/allure-framework/allure-js/releases/tag/v2.0.0-beta.11).
